/**
 * Writes the D1 SQL for Better Auth's tables (user, session, account, verification).
 * D1 can't be reached by the Better Auth CLI, so we compile the migration against
 * an empty in-memory SQLite DB and save it as a wrangler D1 migration.
 *
 *   pnpm db:auth-schema
 */
import { writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { getMigrations } from "better-auth/db/migration";
import { buildAuthOptions } from "../src/lib/auth/options.ts";

const options = buildAuthOptions(new DatabaseSync(":memory:") as never, {
  BETTER_AUTH_SECRET: "schema-generation-only-not-a-real-secret-0123456789",
});
const { compileMigrations } = await getMigrations(options);
const sql = await compileMigrations();
const out = "migrations/0002_better_auth.sql";
writeFileSync(
  out,
  `-- Better Auth tables (generated by scripts/generate-auth-migration.mts, better-auth ${"1.7.7"}).\n${sql.trim()}\n`,
);
console.log(`wrote ${out}`);
